---
# tasks file for kibana

# https://www.elastic.co/downloads/kibana

# Download and install the Public Signing Key
- apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present

- apt: name=apt-transport-https
  args:
    state: present

# Add the repository definition to your /etc/apt/sources.list file
- name: Add Elastic repository
  apt_repository: repo="deb https://artifacts.elastic.co/packages/5.x/apt stable main"
  args:
    state: present
    update_cache: yes

- name: Install Kibana
  apt: name=kibana
  args:
    state: present
    force: yes

#- file:
#    path: /home/kibana
#    state: directory
#    owner: "kibana"
#    group: "kibana"
#    mode: "u=rwx,g=rwx,o-rwx"

- file:
    path: /var/log/kibana
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: "u=rwx,g=rwx,o-rwx"

# Disable? "﻿kibana.service start request repeated too quickly, refusing to start."
# Start service
- service: name=kibana state=started enabled=yes
